In [1]:
import numpy as np

In [6]:
np.random.random()

0.2801751540891263

In [12]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [19]:
np.random.uniform(1,10)

4.11004654338743

In [25]:
np.random.randint(2,20)

15

In [26]:
np.random.randint(1,29,5)

array([10, 10,  8, 23, 26])

In [28]:
np.random.randint(1,100,15).reshape(3,5)

array([[58,  4, 69, 25, 44],
       [77, 27, 53, 81, 42],
       [83, 16, 65, 69, 26]])

In [43]:
a=np.random.randint(1,10,6)
a

array([6, 7, 3, 6, 8, 9])

In [39]:
a[a%2==1]=-1
a

array([ 2,  4, -1, -1, -1, -1])

In [45]:
np.where(a%2==1,-1,a)

array([ 6, -1, -1,  6,  8, -1])

In [46]:
a

array([6, 7, 3, 6, 8, 9])

In [47]:
out=np.where(a%2==1,-1,a)
out

array([ 6, -1, -1,  6,  8, -1])

In [49]:
a=np.random.randint(1,50,10)
a

array([49, 19, 33, 14, 11, 24, 18,  8, 25, 11])

In [52]:
a=np.sort(a)
a

array([ 8, 11, 11, 14, 18, 19, 24, 25, 33, 49])

In [55]:
np.percentile(a,25)

11.75

In [59]:
np.percentile(a,50)

18.5

In [60]:
np.percentile(a,100)

49.0

In [61]:
np.percentile(a,99.8)

48.71199999999999